version: '3.8'
services:

    db:
      container_name: postgres_stock
      image: postgres
      environment:
        POSTGRES_PASSWORD: XXXXXXX
      ports:
        - "5432:5432"
      #   (HOST:CONTAINER)
      volumes:
        - pgdata:/var/lib/postgresql/data/


volumes:
    pgdata:
