# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_ui\ControlCenter.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TinyControlCenter(object):
    def setupUi(self, TinyControlCenter):
        TinyControlCenter.setObjectName("TinyControlCenter")
        TinyControlCenter.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(TinyControlCenter)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 751, 551))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 10, 741, 511))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(20, 60, 381, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(20, 20, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.btn_LoadData = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_LoadData.setGeometry(QtCore.QRect(410, 60, 75, 23))
        self.btn_LoadData.setObjectName("btn_LoadData")
        self.btn_SaveCSV = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_SaveCSV.setGeometry(QtCore.QRect(490, 60, 75, 23))
        self.btn_SaveCSV.setObjectName("btn_SaveCSV")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget.setGeometry(QtCore.QRect(20, 90, 711, 401))
        self.tableWidget.setRowCount(3)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.btn_SaveXLS = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_SaveXLS.setGeometry(QtCore.QRect(570, 60, 75, 23))
        self.btn_SaveXLS.setObjectName("btn_SaveXLS")
        self.tabWidget.addTab(self.tab, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 70, 701, 401))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.btn_RepData = QtWidgets.QPushButton(self.tab_6)
        self.btn_RepData.setGeometry(QtCore.QRect(300, 30, 75, 23))
        self.btn_RepData.setObjectName("btn_RepData")
        self.btn_RepExcel = QtWidgets.QPushButton(self.tab_6)
        self.btn_RepExcel.setGeometry(QtCore.QRect(380, 30, 75, 23))
        self.btn_RepExcel.setObjectName("btn_RepExcel")
        self.dateEdit = QtWidgets.QDateEdit(self.tab_6)
        self.dateEdit.setGeometry(QtCore.QRect(30, 30, 110, 22))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.tab_6)
        self.dateEdit_2.setGeometry(QtCore.QRect(150, 30, 110, 22))
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 120, 80))
        self.groupBox.setObjectName("groupBox")
        self.LANButton = QtWidgets.QPushButton(self.groupBox)
        self.LANButton.setGeometry(QtCore.QRect(20, 20, 75, 23))
        self.LANButton.setObjectName("LANButton")
        self.WLANButton = QtWidgets.QPushButton(self.groupBox)
        self.WLANButton.setGeometry(QtCore.QRect(20, 50, 75, 23))
        self.WLANButton.setObjectName("WLANButton")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_2.setGeometry(QtCore.QRect(0, 10, 111, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.btn_LineBot = QtWidgets.QPushButton(self.tab_4)
        self.btn_LineBot.setGeometry(QtCore.QRect(120, 10, 75, 23))
        self.btn_LineBot.setObjectName("btn_LineBot")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 40, 351, 471))
        self.tableWidget_2.setRowCount(3)
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.btn_SendMail = QtWidgets.QPushButton(self.tab_5)
        self.btn_SendMail.setGeometry(QtCore.QRect(120, 140, 75, 23))
        self.btn_SendMail.setObjectName("btn_SendMail")
        self.tabWidget.addTab(self.tab_5, "")
        TinyControlCenter.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TinyControlCenter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        TinyControlCenter.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TinyControlCenter)
        self.statusbar.setObjectName("statusbar")
        TinyControlCenter.setStatusBar(self.statusbar)

        self.retranslateUi(TinyControlCenter)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(TinyControlCenter)

    def retranslateUi(self, TinyControlCenter):
        _translate = QtCore.QCoreApplication.translate
        TinyControlCenter.setWindowTitle(_translate("TinyControlCenter", "TinyControlCenter"))
        self.groupBox_2.setTitle(_translate("TinyControlCenter", "資料查詢"))
        self.comboBox.setItemText(0, _translate("TinyControlCenter", "ORD"))
        self.comboBox.setItemText(1, _translate("TinyControlCenter", "STK"))
        self.comboBox.setItemText(2, _translate("TinyControlCenter", "MTL"))
        self.comboBox.setItemText(3, _translate("TinyControlCenter", "TQC"))
        self.comboBox.setItemText(4, _translate("TinyControlCenter", "WIP"))
        self.comboBox.setItemText(5, _translate("TinyControlCenter", "CPS"))
        self.comboBox.setItemText(6, _translate("TinyControlCenter", "CR2"))
        self.comboBox.setItemText(7, _translate("TinyControlCenter", "PAY"))
        self.btn_LoadData.setText(_translate("TinyControlCenter", "執行"))
        self.btn_SaveCSV.setText(_translate("TinyControlCenter", "存成CSV"))
        self.btn_SaveXLS.setText(_translate("TinyControlCenter", "存成XLS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("TinyControlCenter", "資料檢索"))
        self.btn_RepData.setText(_translate("TinyControlCenter", "執行"))
        self.btn_RepExcel.setText(_translate("TinyControlCenter", "存檔"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("TinyControlCenter", "日常報告"))
        self.groupBox.setTitle(_translate("TinyControlCenter", "網路切換"))
        self.LANButton.setText(_translate("TinyControlCenter", "區域網路"))
        self.WLANButton.setText(_translate("TinyControlCenter", "WiFi"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("TinyControlCenter", "功能設定"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("TinyControlCenter", "網頁功能"))
        self.comboBox_2.setItemText(0, _translate("TinyControlCenter", "List User"))
        self.comboBox_2.setItemText(1, _translate("TinyControlCenter", "Check Status"))
        self.btn_LineBot.setText(_translate("TinyControlCenter", "執行"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("TinyControlCenter", "LineBot 狀況"))
        self.btn_SendMail.setText(_translate("TinyControlCenter", "寄送信件"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("TinyControlCenter", "郵件"))

