# Generated by Django 2.2 on 2019-12-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRLogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruser',
            name='deptno',
            field=models.CharField(default='', max_length=1),
        ),
    ]
